import type { Grade, RankedCandidate, TallyResponse } from '@star-judge/shared';

export interface MockScenario {
  id: string;
  label: string;
  description: string;
  tally: TallyResponse;
  related?: { id: string; label: string };
}

// ─── Helpers ──────────────────────────────────────────────────────────────────
// gradeCounts shorthand
type GC = { excellent: number; verygood: number; good: number; average: number; fair: number; poor: number };
const gc = (e: number, vg: number, g: number, av: number, f: number, p: number): GC => ({
  excellent: e,
  verygood: vg,
  good: g,
  average: av,
  fair: f,
  poor: p,
});

// Rank-indexed preference lists: rank N prefers the Nth grade, falling back to
// nearest grades that actually have nonzero votes (so the highlight lands on a
// visible segment in the chart).
const DICT_PREFS: Grade[][] = [
  ['excellent', 'verygood', 'good', 'average', 'fair', 'poor'],
  ['verygood', 'good', 'excellent', 'average', 'fair', 'poor'],
  ['good', 'verygood', 'average', 'excellent', 'fair', 'poor'],
  ['average', 'good', 'fair', 'verygood', 'poor', 'excellent'],
  ['fair', 'poor', 'average', 'good', 'verygood', 'excellent'],
  ['poor', 'fair', 'average', 'good', 'verygood', 'excellent'],
];

function pickDictatorGrade(rank: number, counts: GC): Grade {
  const prefs = DICT_PREFS[Math.min(Math.max(rank, 1), 6) - 1];
  return prefs.find((g) => counts[g] > 0) ?? 'poor';
}

// Wraps a dictator array and populates dictatorGrade on each entry, based on
// the candidate's rank and which grades actually received votes.
const d = <T extends Omit<RankedCandidate, 'dictatorGrade'>>(entries: T[]): (T & { dictatorGrade: Grade })[] =>
  entries.map((e) => ({ ...e, dictatorGrade: pickDictatorGrade(e.rank, e.gradeCounts as GC) }));

// ─── Scenario 1: Methods Disagree ────────────────────────────────────────────
// MJ: Catan #1 (Excellent median, polarizing 4E+3P).
// STAR: Pandemic #1 (7 VG = score 28, consistent crowd-pleaser).
// Borda/IRV/Condorcet: Pandemic wins (consistent middle-high beats polarizer).
// Dictator: "Sam" picks Catan (personal enthusiasm).
const diverge: MockScenario = {
  id: 'mock-diverge',
  label: 'Methods Disagree',
  description: 'Same ballot, different winners — proof that the method you choose can pick the game you play.',
  tally: {
    ballotId: 0,
    ballotName: 'Game Night — Methods Compared',
    officialMethod: 'ivstar',
    voteCount: 7,
    mj: [
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 1, totalVotes: 7, gradeCounts: gc(4, 0, 0, 0, 0, 3) },
      { id: 'pandemic', name: 'Pandemic', thumbnail: '', rank: 2, totalVotes: 7, gradeCounts: gc(0, 7, 0, 0, 0, 0) },
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 3, totalVotes: 7, gradeCounts: gc(1, 4, 2, 0, 0, 0) },
      { id: 'codenames', name: 'Codenames', thumbnail: '', rank: 4, totalVotes: 7, gradeCounts: gc(0, 4, 3, 0, 0, 0) },
      { id: 'ttr', name: 'Ticket to Ride', thumbnail: '', rank: 5, totalVotes: 7, gradeCounts: gc(0, 0, 4, 3, 0, 0) },
    ],
    star: [
      {
        id: 'pandemic',
        name: 'Pandemic',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        starScore: 28,
        inRunoff: true,
        gradeCounts: gc(0, 7, 0, 0, 0, 0),
      },
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        starScore: 27,
        inRunoff: true,
        gradeCounts: gc(1, 4, 2, 0, 0, 0),
      },
      {
        id: 'codenames',
        name: 'Codenames',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        starScore: 25,
        gradeCounts: gc(0, 4, 3, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 4,
        totalVotes: 7,
        starScore: 20,
        gradeCounts: gc(4, 0, 0, 0, 0, 3),
      },
      {
        id: 'ttr',
        name: 'Ticket to Ride',
        thumbnail: '',
        rank: 5,
        totalVotes: 7,
        starScore: 18,
        gradeCounts: gc(0, 0, 4, 3, 0, 0),
      },
    ],
    ivmj: [
      { id: 'pandemic', name: 'Pandemic', thumbnail: '', rank: 1, totalVotes: 7, gradeCounts: gc(0, 7, 0, 0, 0, 0) },
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 2, totalVotes: 7, gradeCounts: gc(1, 4, 2, 0, 0, 0) },
      { id: 'codenames', name: 'Codenames', thumbnail: '', rank: 3, totalVotes: 7, gradeCounts: gc(0, 4, 3, 0, 0, 0) },
      { id: 'ttr', name: 'Ticket to Ride', thumbnail: '', rank: 4, totalVotes: 7, gradeCounts: gc(0, 0, 4, 3, 0, 0) },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 5,
        totalVotes: 7,
        vetoed: true,
        hardPassCount: 3,
        gradeCounts: gc(4, 0, 0, 0, 0, 3),
      },
    ],
    ivstar: [
      {
        id: 'pandemic',
        name: 'Pandemic',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        starScore: 28,
        inRunoff: true,
        gradeCounts: gc(0, 7, 0, 0, 0, 0),
      },
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        starScore: 27,
        inRunoff: true,
        gradeCounts: gc(1, 4, 2, 0, 0, 0),
      },
      {
        id: 'codenames',
        name: 'Codenames',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        starScore: 25,
        gradeCounts: gc(0, 4, 3, 0, 0, 0),
      },
      {
        id: 'ttr',
        name: 'Ticket to Ride',
        thumbnail: '',
        rank: 4,
        totalVotes: 7,
        starScore: 18,
        gradeCounts: gc(0, 0, 4, 3, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 5,
        totalVotes: 7,
        starScore: 20,
        vetoed: true,
        hardPassCount: 3,
        gradeCounts: gc(4, 0, 0, 0, 0, 3),
      },
    ],
    // Borda: Pandemic wins (consistently high-ranked by all 7 voters)
    borda: [
      {
        id: 'pandemic',
        name: 'Pandemic',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        bordaScore: 21,
        gradeCounts: gc(0, 7, 0, 0, 0, 0),
      },
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        bordaScore: 20,
        gradeCounts: gc(1, 4, 2, 0, 0, 0),
      },
      {
        id: 'codenames',
        name: 'Codenames',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        bordaScore: 18,
        gradeCounts: gc(0, 4, 3, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 4,
        totalVotes: 7,
        bordaScore: 16,
        gradeCounts: gc(4, 0, 0, 0, 0, 3),
      },
      {
        id: 'ttr',
        name: 'Ticket to Ride',
        thumbnail: '',
        rank: 5,
        totalVotes: 7,
        bordaScore: 11,
        gradeCounts: gc(0, 0, 4, 3, 0, 0),
      },
    ],
    // IRV: TTR → Codenames → Wingspan → Catan → Pandemic wins
    irv: [
      { id: 'pandemic', name: 'Pandemic', thumbnail: '', rank: 1, totalVotes: 7, gradeCounts: gc(0, 7, 0, 0, 0, 0) },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        irvElimRound: 4,
        gradeCounts: gc(4, 0, 0, 0, 0, 3),
      },
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        irvElimRound: 3,
        gradeCounts: gc(1, 4, 2, 0, 0, 0),
      },
      {
        id: 'codenames',
        name: 'Codenames',
        thumbnail: '',
        rank: 4,
        totalVotes: 7,
        irvElimRound: 2,
        gradeCounts: gc(0, 4, 3, 0, 0, 0),
      },
      {
        id: 'ttr',
        name: 'Ticket to Ride',
        thumbnail: '',
        rank: 5,
        totalVotes: 7,
        irvElimRound: 1,
        gradeCounts: gc(0, 0, 4, 3, 0, 0),
      },
    ],
    // Condorcet: Pandemic beats all head-to-head (consistent VG beats polarizing or mediocre)
    condorcet: [
      {
        id: 'pandemic',
        name: 'Pandemic',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        pairwiseWins: 4,
        gradeCounts: gc(0, 7, 0, 0, 0, 0),
      },
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        pairwiseWins: 3,
        gradeCounts: gc(1, 4, 2, 0, 0, 0),
      },
      {
        id: 'codenames',
        name: 'Codenames',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        pairwiseWins: 2,
        gradeCounts: gc(0, 4, 3, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 4,
        totalVotes: 7,
        pairwiseWins: 1,
        gradeCounts: gc(4, 0, 0, 0, 0, 3),
      },
      {
        id: 'ttr',
        name: 'Ticket to Ride',
        thumbnail: '',
        rank: 5,
        totalVotes: 7,
        pairwiseWins: 0,
        gradeCounts: gc(0, 0, 4, 3, 0, 0),
      },
    ],
    condorcetParadox: false,
    // Dictator: Sam voted last and loves Catan despite the haters
    dictator: d([
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 1, totalVotes: 7, gradeCounts: gc(4, 0, 0, 0, 0, 3) },
      { id: 'pandemic', name: 'Pandemic', thumbnail: '', rank: 2, totalVotes: 7, gradeCounts: gc(0, 7, 0, 0, 0, 0) },
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 2, totalVotes: 7, gradeCounts: gc(1, 4, 2, 0, 0, 0) },
      { id: 'codenames', name: 'Codenames', thumbnail: '', rank: 4, totalVotes: 7, gradeCounts: gc(0, 4, 3, 0, 0, 0) },
      { id: 'ttr', name: 'Ticket to Ride', thumbnail: '', rank: 4, totalVotes: 7, gradeCounts: gc(0, 0, 4, 3, 0, 0) },
    ]),
    dictatorName: 'Sam',
  },
};

// ─── Scenario 2: Methods Agree ────────────────────────────────────────────────
const agree: MockScenario = {
  id: 'mock-agree',
  label: 'Methods Agree',
  description: 'The baseline case: when voters agree, all eight methods agree. Everyone loves Wingspan.',
  tally: {
    ballotId: 0,
    ballotName: 'Easy Night In',
    officialMethod: 'ivstar',
    voteCount: 5,
    mj: [
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 5, gradeCounts: gc(4, 1, 0, 0, 0, 0) },
      { id: 'codenames', name: 'Codenames', thumbnail: '', rank: 2, totalVotes: 5, gradeCounts: gc(1, 2, 2, 0, 0, 0) },
      { id: 'azul', name: 'Azul', thumbnail: '', rank: 3, totalVotes: 5, gradeCounts: gc(0, 1, 2, 1, 1, 0) },
    ],
    star: [
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 5,
        starScore: 24,
        inRunoff: true,
        gradeCounts: gc(4, 1, 0, 0, 0, 0),
      },
      {
        id: 'codenames',
        name: 'Codenames',
        thumbnail: '',
        rank: 2,
        totalVotes: 5,
        starScore: 17,
        inRunoff: true,
        gradeCounts: gc(1, 2, 2, 0, 0, 0),
      },
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 3,
        totalVotes: 5,
        starScore: 13,
        gradeCounts: gc(0, 1, 2, 1, 1, 0),
      },
    ],
    ivmj: [
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 5, gradeCounts: gc(4, 1, 0, 0, 0, 0) },
      { id: 'codenames', name: 'Codenames', thumbnail: '', rank: 2, totalVotes: 5, gradeCounts: gc(1, 2, 2, 0, 0, 0) },
      { id: 'azul', name: 'Azul', thumbnail: '', rank: 3, totalVotes: 5, gradeCounts: gc(0, 1, 2, 1, 1, 0) },
    ],
    ivstar: [
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 5,
        starScore: 24,
        inRunoff: true,
        gradeCounts: gc(4, 1, 0, 0, 0, 0),
      },
      {
        id: 'codenames',
        name: 'Codenames',
        thumbnail: '',
        rank: 2,
        totalVotes: 5,
        starScore: 17,
        inRunoff: true,
        gradeCounts: gc(1, 2, 2, 0, 0, 0),
      },
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 3,
        totalVotes: 5,
        starScore: 13,
        gradeCounts: gc(0, 1, 2, 1, 1, 0),
      },
    ],
    borda: [
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 5,
        bordaScore: 9,
        gradeCounts: gc(4, 1, 0, 0, 0, 0),
      },
      {
        id: 'codenames',
        name: 'Codenames',
        thumbnail: '',
        rank: 2,
        totalVotes: 5,
        bordaScore: 6,
        gradeCounts: gc(1, 2, 2, 0, 0, 0),
      },
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 3,
        totalVotes: 5,
        bordaScore: 3,
        gradeCounts: gc(0, 1, 2, 1, 1, 0),
      },
    ],
    irv: [
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 5, gradeCounts: gc(4, 1, 0, 0, 0, 0) },
      {
        id: 'codenames',
        name: 'Codenames',
        thumbnail: '',
        rank: 2,
        totalVotes: 5,
        irvElimRound: 2,
        gradeCounts: gc(1, 2, 2, 0, 0, 0),
      },
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 3,
        totalVotes: 5,
        irvElimRound: 1,
        gradeCounts: gc(0, 1, 2, 1, 1, 0),
      },
    ],
    condorcet: [
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 5,
        pairwiseWins: 2,
        gradeCounts: gc(4, 1, 0, 0, 0, 0),
      },
      {
        id: 'codenames',
        name: 'Codenames',
        thumbnail: '',
        rank: 2,
        totalVotes: 5,
        pairwiseWins: 1,
        gradeCounts: gc(1, 2, 2, 0, 0, 0),
      },
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 3,
        totalVotes: 5,
        pairwiseWins: 0,
        gradeCounts: gc(0, 1, 2, 1, 1, 0),
      },
    ],
    condorcetParadox: false,
    dictator: d([
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 5, gradeCounts: gc(4, 1, 0, 0, 0, 0) },
      { id: 'codenames', name: 'Codenames', thumbnail: '', rank: 2, totalVotes: 5, gradeCounts: gc(1, 2, 2, 0, 0, 0) },
      { id: 'azul', name: 'Azul', thumbnail: '', rank: 3, totalVotes: 5, gradeCounts: gc(0, 1, 2, 1, 1, 0) },
    ]),
    dictatorName: 'Pat',
  },
};

// ─── Scenario: Borda's Broad-Support Winner ──────────────────────────────────
// Two rival factions (euro-gamers love Catan, epic-gamers love Twilight Imperium)
// polarize around their favorite and give the rival a hard pass. Codenames is
// everyone's calm second choice. STAR (score=19), MJ (median=verygood), and IRV
// all pick the polarizer Catan. But Borda — which rewards per-ballot *position*
// rather than raw grades — uniquely lifts Codenames to #1 on its rank-sum.
// Condorcet agrees (Codenames beats both factions head-to-head) and IV methods
// veto both polarizers outright. Sam votes last, tipping IRV.
const bordaConsensus: MockScenario = {
  id: 'mock-borda-consensus',
  label: 'Broad Support Wins',
  description: "STAR/MJ/IRV pick the polarizing favorite. Borda and Condorcet lift the consensus runner-up — the game nobody hates.",
  tally: {
    ballotId: 0,
    ballotName: 'Euros vs Epics',
    officialMethod: 'borda',
    voteCount: 7,
    mj: [
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 1, totalVotes: 7, gradeCounts: gc(3, 1, 0, 0, 0, 3) },
      { id: 'codenames', name: 'Codenames', thumbnail: '', rank: 2, totalVotes: 7, gradeCounts: gc(1, 0, 0, 0, 6, 0) },
      { id: 'ti4', name: 'Twilight Imperium', thumbnail: '', rank: 3, totalVotes: 7, gradeCounts: gc(3, 0, 0, 0, 0, 4) },
    ],
    star: [
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        starScore: 19,
        inRunoff: true,
        gradeCounts: gc(3, 1, 0, 0, 0, 3),
      },
      {
        id: 'ti4',
        name: 'Twilight Imperium',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        starScore: 15,
        inRunoff: true,
        gradeCounts: gc(3, 0, 0, 0, 0, 4),
      },
      {
        id: 'codenames',
        name: 'Codenames',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        starScore: 11,
        gradeCounts: gc(1, 0, 0, 0, 6, 0),
      },
    ],
    ivmj: [
      {
        id: 'codenames',
        name: 'Codenames',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        gradeCounts: gc(1, 0, 0, 0, 6, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        vetoed: true,
        hardPassCount: 3,
        gradeCounts: gc(3, 1, 0, 0, 0, 3),
      },
      {
        id: 'ti4',
        name: 'Twilight Imperium',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        vetoed: true,
        hardPassCount: 4,
        gradeCounts: gc(3, 0, 0, 0, 0, 4),
      },
    ],
    ivstar: [
      {
        id: 'codenames',
        name: 'Codenames',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        starScore: 11,
        inRunoff: true,
        gradeCounts: gc(1, 0, 0, 0, 6, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        starScore: 19,
        vetoed: true,
        hardPassCount: 3,
        gradeCounts: gc(3, 1, 0, 0, 0, 3),
      },
      {
        id: 'ti4',
        name: 'Twilight Imperium',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        starScore: 15,
        vetoed: true,
        hardPassCount: 4,
        gradeCounts: gc(3, 0, 0, 0, 0, 4),
      },
    ],
    borda: [
      {
        id: 'codenames',
        name: 'Codenames',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        bordaScore: 8,
        gradeCounts: gc(1, 0, 0, 0, 6, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        bordaScore: 7,
        gradeCounts: gc(3, 1, 0, 0, 0, 3),
      },
      {
        id: 'ti4',
        name: 'Twilight Imperium',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        bordaScore: 6,
        gradeCounts: gc(3, 0, 0, 0, 0, 4),
      },
    ],
    irv: [
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 1, totalVotes: 7, gradeCounts: gc(3, 1, 0, 0, 0, 3) },
      {
        id: 'ti4',
        name: 'Twilight Imperium',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        irvElimRound: 2,
        gradeCounts: gc(3, 0, 0, 0, 0, 4),
      },
      {
        id: 'codenames',
        name: 'Codenames',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        irvElimRound: 1,
        gradeCounts: gc(1, 0, 0, 0, 6, 0),
      },
    ],
    condorcet: [
      {
        id: 'codenames',
        name: 'Codenames',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        pairwiseWins: 2,
        gradeCounts: gc(1, 0, 0, 0, 6, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        pairwiseWins: 1,
        gradeCounts: gc(3, 1, 0, 0, 0, 3),
      },
      {
        id: 'ti4',
        name: 'Twilight Imperium',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        pairwiseWins: 0,
        gradeCounts: gc(3, 0, 0, 0, 0, 4),
      },
    ],
    condorcetParadox: false,
    dictator: d([
      { id: 'codenames', name: 'Codenames', thumbnail: '', rank: 1, totalVotes: 7, gradeCounts: gc(1, 0, 0, 0, 6, 0) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 2, totalVotes: 7, gradeCounts: gc(3, 1, 0, 0, 0, 3) },
      { id: 'ti4', name: 'Twilight Imperium', thumbnail: '', rank: 3, totalVotes: 7, gradeCounts: gc(3, 0, 0, 0, 0, 4) },
    ]),
    dictatorName: 'Sam',
  },
};

// ─── Scenario 3: No Votes ─────────────────────────────────────────────────────
const noVotes: MockScenario = {
  id: 'mock-novotes',
  label: 'No Votes Yet',
  description: 'The ballot is open but nobody has voted yet.',
  tally: {
    ballotId: 0,
    ballotName: 'Friday Night Games',
    officialMethod: 'ivstar',
    voteCount: 0,
    mj: [],
    star: [],
    ivmj: [],
    ivstar: [],
    borda: [],
    irv: [],
    condorcet: [],
    condorcetParadox: false,
    dictator: d([]),
    dictatorName: null,
  },
};

// ─── Scenario 4: Perfect Tie ──────────────────────────────────────────────────
// Catan and Pandemic have identical grade distributions — every method ties.
const tie: MockScenario = {
  id: 'mock-tie',
  label: 'Perfect Tie',
  description: 'Two games have identical ratings — every method deadlocks at #1 except Dictator.',
  tally: {
    ballotId: 0,
    ballotName: 'Impossible to Choose',
    officialMethod: 'ivstar',
    voteCount: 7,
    mj: [
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 1, totalVotes: 7, gradeCounts: gc(3, 2, 2, 0, 0, 0) },
      { id: 'pandemic', name: 'Pandemic', thumbnail: '', rank: 1, totalVotes: 7, gradeCounts: gc(3, 2, 2, 0, 0, 0) },
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 3, totalVotes: 7, gradeCounts: gc(0, 1, 3, 3, 0, 0) },
    ],
    star: [
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        starScore: 29,
        inRunoff: true,
        gradeCounts: gc(3, 2, 2, 0, 0, 0),
      },
      {
        id: 'pandemic',
        name: 'Pandemic',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        starScore: 29,
        inRunoff: true,
        gradeCounts: gc(3, 2, 2, 0, 0, 0),
      },
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        starScore: 15,
        gradeCounts: gc(0, 1, 3, 3, 0, 0),
      },
    ],
    ivmj: [
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 1, totalVotes: 7, gradeCounts: gc(3, 2, 2, 0, 0, 0) },
      { id: 'pandemic', name: 'Pandemic', thumbnail: '', rank: 1, totalVotes: 7, gradeCounts: gc(3, 2, 2, 0, 0, 0) },
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 3, totalVotes: 7, gradeCounts: gc(0, 1, 3, 3, 0, 0) },
    ],
    ivstar: [
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        starScore: 29,
        inRunoff: true,
        gradeCounts: gc(3, 2, 2, 0, 0, 0),
      },
      {
        id: 'pandemic',
        name: 'Pandemic',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        starScore: 29,
        inRunoff: true,
        gradeCounts: gc(3, 2, 2, 0, 0, 0),
      },
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        starScore: 15,
        gradeCounts: gc(0, 1, 3, 3, 0, 0),
      },
    ],
    borda: [
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        bordaScore: 11,
        gradeCounts: gc(3, 2, 2, 0, 0, 0),
      },
      {
        id: 'pandemic',
        name: 'Pandemic',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        bordaScore: 11,
        gradeCounts: gc(3, 2, 2, 0, 0, 0),
      },
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        bordaScore: 6,
        gradeCounts: gc(0, 1, 3, 3, 0, 0),
      },
    ],
    irv: [
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 1, totalVotes: 7, gradeCounts: gc(3, 2, 2, 0, 0, 0) },
      { id: 'pandemic', name: 'Pandemic', thumbnail: '', rank: 1, totalVotes: 7, gradeCounts: gc(3, 2, 2, 0, 0, 0) },
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        irvElimRound: 1,
        gradeCounts: gc(0, 1, 3, 3, 0, 0),
      },
    ],
    condorcet: [
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        pairwiseWins: 1,
        gradeCounts: gc(3, 2, 2, 0, 0, 0),
      },
      {
        id: 'pandemic',
        name: 'Pandemic',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        pairwiseWins: 1,
        gradeCounts: gc(3, 2, 2, 0, 0, 0),
      },
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        pairwiseWins: 0,
        gradeCounts: gc(0, 1, 3, 3, 0, 0),
      },
    ],
    condorcetParadox: false,
    dictator: d([
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 1, totalVotes: 7, gradeCounts: gc(3, 2, 2, 0, 0, 0) },
      { id: 'pandemic', name: 'Pandemic', thumbnail: '', rank: 2, totalVotes: 7, gradeCounts: gc(3, 2, 2, 0, 0, 0) },
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 3, totalVotes: 7, gradeCounts: gc(0, 1, 3, 3, 0, 0) },
    ]),
    dictatorName: 'Jordan',
  },
};

// ─── Scenario 5: STAR Runoff Flip ─────────────────────────────────────────────
// Cosmic scores highest (25) but Terra wins the runoff 5-2 head-to-head.
// IRV + Condorcet also pick Terra (Terra is everyone's #1 or #2 except 2 HP voters).
// IV vetoes Terra (2 HP > 0). Dictator "Jordan" is a Cosmic fan.
const runoffFlip: MockScenario = {
  id: 'mock-runoff-flip',
  label: 'STAR Runoff Flip',
  description: 'The highest-scoring game loses the runoff — majority preferred the runner-up head-to-head.',
  tally: {
    ballotId: 0,
    ballotName: 'STAR Runoff Demo',
    officialMethod: 'star',
    voteCount: 7,
    mj: [
      { id: 'terra', name: 'Terra Mystica', thumbnail: '', rank: 1, totalVotes: 7, gradeCounts: gc(0, 5, 0, 0, 0, 2) },
      {
        id: 'cosmic',
        name: 'Cosmic Encounter',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        gradeCounts: gc(2, 0, 5, 0, 0, 0),
      },
      { id: 'chess', name: 'Chess', thumbnail: '', rank: 3, totalVotes: 7, gradeCounts: gc(0, 0, 3, 4, 0, 0) },
    ],
    star: [
      {
        id: 'terra',
        name: 'Terra Mystica',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        starScore: 20,
        inRunoff: true,
        gradeCounts: gc(0, 5, 0, 0, 0, 2),
      },
      {
        id: 'cosmic',
        name: 'Cosmic Encounter',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        starScore: 25,
        inRunoff: true,
        gradeCounts: gc(2, 0, 5, 0, 0, 0),
      },
      {
        id: 'chess',
        name: 'Chess',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        starScore: 17,
        gradeCounts: gc(0, 0, 3, 4, 0, 0),
      },
    ],
    ivmj: [
      {
        id: 'cosmic',
        name: 'Cosmic Encounter',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        gradeCounts: gc(2, 0, 5, 0, 0, 0),
      },
      { id: 'chess', name: 'Chess', thumbnail: '', rank: 2, totalVotes: 7, gradeCounts: gc(0, 0, 3, 4, 0, 0) },
      {
        id: 'terra',
        name: 'Terra Mystica',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        vetoed: true,
        hardPassCount: 2,
        gradeCounts: gc(0, 5, 0, 0, 0, 2),
      },
    ],
    ivstar: [
      {
        id: 'cosmic',
        name: 'Cosmic Encounter',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        starScore: 25,
        inRunoff: true,
        gradeCounts: gc(2, 0, 5, 0, 0, 0),
      },
      {
        id: 'chess',
        name: 'Chess',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        starScore: 17,
        inRunoff: true,
        gradeCounts: gc(0, 0, 3, 4, 0, 0),
      },
      {
        id: 'terra',
        name: 'Terra Mystica',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        starScore: 20,
        vetoed: true,
        hardPassCount: 2,
        gradeCounts: gc(0, 5, 0, 0, 0, 2),
      },
    ],
    // Borda: Terra wins (5 VG voters rank it highly; Cosmic's HP voters drag it down)
    borda: [
      {
        id: 'terra',
        name: 'Terra Mystica',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        bordaScore: 10,
        gradeCounts: gc(0, 5, 0, 0, 0, 2),
      },
      {
        id: 'cosmic',
        name: 'Cosmic Encounter',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        bordaScore: 9,
        gradeCounts: gc(2, 0, 5, 0, 0, 0),
      },
      {
        id: 'chess',
        name: 'Chess',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        bordaScore: 5,
        gradeCounts: gc(0, 0, 3, 4, 0, 0),
      },
    ],
    // IRV: Chess elim round 1, then Terra beats Cosmic (Terra has 5 first-choice VG voters)
    irv: [
      { id: 'terra', name: 'Terra Mystica', thumbnail: '', rank: 1, totalVotes: 7, gradeCounts: gc(0, 5, 0, 0, 0, 2) },
      {
        id: 'cosmic',
        name: 'Cosmic Encounter',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        irvElimRound: 2,
        gradeCounts: gc(2, 0, 5, 0, 0, 0),
      },
      {
        id: 'chess',
        name: 'Chess',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        irvElimRound: 1,
        gradeCounts: gc(0, 0, 3, 4, 0, 0),
      },
    ],
    // Condorcet: Terra beats all head-to-head (5 VG voters prefer Terra over everyone)
    condorcet: [
      {
        id: 'terra',
        name: 'Terra Mystica',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        pairwiseWins: 2,
        gradeCounts: gc(0, 5, 0, 0, 0, 2),
      },
      {
        id: 'cosmic',
        name: 'Cosmic Encounter',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        pairwiseWins: 1,
        gradeCounts: gc(2, 0, 5, 0, 0, 0),
      },
      {
        id: 'chess',
        name: 'Chess',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        pairwiseWins: 0,
        gradeCounts: gc(0, 0, 3, 4, 0, 0),
      },
    ],
    condorcetParadox: false,
    // Dictator: Jordan voted last and is a Cosmic Encounter devotee
    dictator: d([
      {
        id: 'cosmic',
        name: 'Cosmic Encounter',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        gradeCounts: gc(2, 0, 5, 0, 0, 0),
      },
      { id: 'terra', name: 'Terra Mystica', thumbnail: '', rank: 2, totalVotes: 7, gradeCounts: gc(0, 5, 0, 0, 0, 2) },
      { id: 'chess', name: 'Chess', thumbnail: '', rank: 3, totalVotes: 7, gradeCounts: gc(0, 0, 3, 4, 0, 0) },
    ]),
    dictatorName: 'Jordan',
  },
};

// ─── Scenario 6: Single Vote ──────────────────────────────────────────────────
const oneVote: MockScenario = {
  id: 'mock-onevote',
  label: 'Single Vote',
  description: "Only one voter so far — rankings are just that person's ratings.",
  tally: {
    ballotId: 0,
    ballotName: 'Just Me So Far',
    officialMethod: 'ivstar',
    voteCount: 1,
    mj: [
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 1, gradeCounts: gc(1, 0, 0, 0, 0, 0) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 2, totalVotes: 1, gradeCounts: gc(0, 0, 1, 0, 0, 0) },
      { id: 'codenames', name: 'Codenames', thumbnail: '', rank: 3, totalVotes: 1, gradeCounts: gc(0, 0, 0, 0, 1, 0) },
    ],
    star: [
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 1,
        starScore: 5,
        inRunoff: true,
        gradeCounts: gc(1, 0, 0, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 1,
        starScore: 3,
        inRunoff: true,
        gradeCounts: gc(0, 0, 1, 0, 0, 0),
      },
      {
        id: 'codenames',
        name: 'Codenames',
        thumbnail: '',
        rank: 3,
        totalVotes: 1,
        starScore: 1,
        gradeCounts: gc(0, 0, 0, 0, 1, 0),
      },
    ],
    ivmj: [
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 1, gradeCounts: gc(1, 0, 0, 0, 0, 0) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 2, totalVotes: 1, gradeCounts: gc(0, 0, 1, 0, 0, 0) },
      { id: 'codenames', name: 'Codenames', thumbnail: '', rank: 3, totalVotes: 1, gradeCounts: gc(0, 0, 0, 0, 1, 0) },
    ],
    ivstar: [
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 1,
        starScore: 5,
        inRunoff: true,
        gradeCounts: gc(1, 0, 0, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 1,
        starScore: 3,
        inRunoff: true,
        gradeCounts: gc(0, 0, 1, 0, 0, 0),
      },
      {
        id: 'codenames',
        name: 'Codenames',
        thumbnail: '',
        rank: 3,
        totalVotes: 1,
        starScore: 1,
        gradeCounts: gc(0, 0, 0, 0, 1, 0),
      },
    ],
    borda: [
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 1,
        bordaScore: 2,
        gradeCounts: gc(1, 0, 0, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 1,
        bordaScore: 1,
        gradeCounts: gc(0, 0, 1, 0, 0, 0),
      },
      {
        id: 'codenames',
        name: 'Codenames',
        thumbnail: '',
        rank: 3,
        totalVotes: 1,
        bordaScore: 0,
        gradeCounts: gc(0, 0, 0, 0, 1, 0),
      },
    ],
    irv: [
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 1, gradeCounts: gc(1, 0, 0, 0, 0, 0) },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 1,
        irvElimRound: 2,
        gradeCounts: gc(0, 0, 1, 0, 0, 0),
      },
      {
        id: 'codenames',
        name: 'Codenames',
        thumbnail: '',
        rank: 3,
        totalVotes: 1,
        irvElimRound: 1,
        gradeCounts: gc(0, 0, 0, 0, 1, 0),
      },
    ],
    condorcet: [
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 1,
        pairwiseWins: 2,
        gradeCounts: gc(1, 0, 0, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 1,
        pairwiseWins: 1,
        gradeCounts: gc(0, 0, 1, 0, 0, 0),
      },
      {
        id: 'codenames',
        name: 'Codenames',
        thumbnail: '',
        rank: 3,
        totalVotes: 1,
        pairwiseWins: 0,
        gradeCounts: gc(0, 0, 0, 0, 1, 0),
      },
    ],
    condorcetParadox: false,
    // The only voter is the dictator by default
    dictator: d([
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 1, gradeCounts: gc(1, 0, 0, 0, 0, 0) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 2, totalVotes: 1, gradeCounts: gc(0, 0, 1, 0, 0, 0) },
      { id: 'codenames', name: 'Codenames', thumbnail: '', rank: 3, totalVotes: 1, gradeCounts: gc(0, 0, 0, 0, 1, 0) },
    ]),
    dictatorName: 'Riley',
  },
};

// ─── Scenario 7: Veto — No Effect (Equal HP Counts) ──────────────────────────
const vetoNodiff: MockScenario = {
  id: 'mock-veto-nodiff',
  label: 'Veto — No Effect',
  description: "Veto isn't a trump card — when every game has the same Hard Pass count, the IV methods fall through and the raw winners stand.",
  tally: {
    ballotId: 0,
    ballotName: 'Equal Hard Passes',
    officialMethod: 'ivmj',
    voteCount: 5,
    mj: [
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 5, gradeCounts: gc(3, 1, 0, 0, 0, 1) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 2, totalVotes: 5, gradeCounts: gc(0, 3, 1, 0, 0, 1) },
      { id: 'azul', name: 'Azul', thumbnail: '', rank: 3, totalVotes: 5, gradeCounts: gc(0, 0, 2, 2, 0, 1) },
    ],
    star: [
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 5,
        starScore: 19,
        inRunoff: true,
        gradeCounts: gc(3, 1, 0, 0, 0, 1),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 5,
        starScore: 15,
        inRunoff: true,
        gradeCounts: gc(0, 3, 1, 0, 0, 1),
      },
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 3,
        totalVotes: 5,
        starScore: 10,
        gradeCounts: gc(0, 0, 2, 2, 0, 1),
      },
    ],
    ivmj: [
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 5, gradeCounts: gc(3, 1, 0, 0, 0, 1) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 2, totalVotes: 5, gradeCounts: gc(0, 3, 1, 0, 0, 1) },
      { id: 'azul', name: 'Azul', thumbnail: '', rank: 3, totalVotes: 5, gradeCounts: gc(0, 0, 2, 2, 0, 1) },
    ],
    ivstar: [
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 5,
        starScore: 19,
        inRunoff: true,
        gradeCounts: gc(3, 1, 0, 0, 0, 1),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 5,
        starScore: 15,
        inRunoff: true,
        gradeCounts: gc(0, 3, 1, 0, 0, 1),
      },
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 3,
        totalVotes: 5,
        starScore: 10,
        gradeCounts: gc(0, 0, 2, 2, 0, 1),
      },
    ],
    borda: [
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 5,
        bordaScore: 8,
        gradeCounts: gc(3, 1, 0, 0, 0, 1),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 5,
        bordaScore: 6,
        gradeCounts: gc(0, 3, 1, 0, 0, 1),
      },
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 3,
        totalVotes: 5,
        bordaScore: 3,
        gradeCounts: gc(0, 0, 2, 2, 0, 1),
      },
    ],
    irv: [
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 5, gradeCounts: gc(3, 1, 0, 0, 0, 1) },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 5,
        irvElimRound: 2,
        gradeCounts: gc(0, 3, 1, 0, 0, 1),
      },
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 3,
        totalVotes: 5,
        irvElimRound: 1,
        gradeCounts: gc(0, 0, 2, 2, 0, 1),
      },
    ],
    condorcet: [
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 5,
        pairwiseWins: 2,
        gradeCounts: gc(3, 1, 0, 0, 0, 1),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 5,
        pairwiseWins: 1,
        gradeCounts: gc(0, 3, 1, 0, 0, 1),
      },
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 3,
        totalVotes: 5,
        pairwiseWins: 0,
        gradeCounts: gc(0, 0, 2, 2, 0, 1),
      },
    ],
    condorcetParadox: false,
    dictator: d([
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 1, totalVotes: 5, gradeCounts: gc(0, 3, 1, 0, 0, 1) },
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 2, totalVotes: 5, gradeCounts: gc(3, 1, 0, 0, 0, 1) },
      { id: 'azul', name: 'Azul', thumbnail: '', rank: 3, totalVotes: 5, gradeCounts: gc(0, 0, 2, 2, 0, 1) },
    ]),
    dictatorName: 'Sam',
  },
};

// ─── Scenario 8: Veto — One Survivor ─────────────────────────────────────────
const vetoOneSurvivor: MockScenario = {
  id: 'mock-veto-onesurvivor',
  label: 'Veto — One Survivor',
  description: 'Only one game escapes the veto — it wins both IV methods by default.',
  tally: {
    ballotId: 0,
    ballotName: 'Mass Disqualification',
    officialMethod: 'ivstar',
    voteCount: 6,
    mj: [
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 1, totalVotes: 6, gradeCounts: gc(4, 0, 0, 0, 0, 2) },
      { id: 'pandemic', name: 'Pandemic', thumbnail: '', rank: 2, totalVotes: 6, gradeCounts: gc(3, 0, 0, 0, 0, 3) },
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 3, totalVotes: 6, gradeCounts: gc(2, 4, 0, 0, 0, 0) },
    ],
    star: [
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 6,
        starScore: 26,
        inRunoff: true,
        gradeCounts: gc(2, 4, 0, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 6,
        starScore: 20,
        inRunoff: true,
        gradeCounts: gc(4, 0, 0, 0, 0, 2),
      },
      {
        id: 'pandemic',
        name: 'Pandemic',
        thumbnail: '',
        rank: 3,
        totalVotes: 6,
        starScore: 15,
        gradeCounts: gc(3, 0, 0, 0, 0, 3),
      },
    ],
    ivmj: [
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 6, gradeCounts: gc(2, 4, 0, 0, 0, 0) },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 6,
        vetoed: true,
        hardPassCount: 2,
        gradeCounts: gc(4, 0, 0, 0, 0, 2),
      },
      {
        id: 'pandemic',
        name: 'Pandemic',
        thumbnail: '',
        rank: 3,
        totalVotes: 6,
        vetoed: true,
        hardPassCount: 3,
        gradeCounts: gc(3, 0, 0, 0, 0, 3),
      },
    ],
    ivstar: [
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 6,
        starScore: 26,
        inRunoff: true,
        gradeCounts: gc(2, 4, 0, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 6,
        starScore: 20,
        vetoed: true,
        hardPassCount: 2,
        gradeCounts: gc(4, 0, 0, 0, 0, 2),
      },
      {
        id: 'pandemic',
        name: 'Pandemic',
        thumbnail: '',
        rank: 3,
        totalVotes: 6,
        starScore: 15,
        vetoed: true,
        hardPassCount: 3,
        gradeCounts: gc(3, 0, 0, 0, 0, 3),
      },
    ],
    borda: [
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 6,
        bordaScore: 10,
        gradeCounts: gc(2, 4, 0, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 6,
        bordaScore: 8,
        gradeCounts: gc(4, 0, 0, 0, 0, 2),
      },
      {
        id: 'pandemic',
        name: 'Pandemic',
        thumbnail: '',
        rank: 3,
        totalVotes: 6,
        bordaScore: 6,
        gradeCounts: gc(3, 0, 0, 0, 0, 3),
      },
    ],
    irv: [
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 6, gradeCounts: gc(2, 4, 0, 0, 0, 0) },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 6,
        irvElimRound: 2,
        gradeCounts: gc(4, 0, 0, 0, 0, 2),
      },
      {
        id: 'pandemic',
        name: 'Pandemic',
        thumbnail: '',
        rank: 3,
        totalVotes: 6,
        irvElimRound: 1,
        gradeCounts: gc(3, 0, 0, 0, 0, 3),
      },
    ],
    condorcet: [
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 6,
        pairwiseWins: 2,
        gradeCounts: gc(2, 4, 0, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 6,
        pairwiseWins: 1,
        gradeCounts: gc(4, 0, 0, 0, 0, 2),
      },
      {
        id: 'pandemic',
        name: 'Pandemic',
        thumbnail: '',
        rank: 3,
        totalVotes: 6,
        pairwiseWins: 0,
        gradeCounts: gc(3, 0, 0, 0, 0, 3),
      },
    ],
    condorcetParadox: false,
    dictator: d([
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 1, totalVotes: 6, gradeCounts: gc(4, 0, 0, 0, 0, 2) },
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 2, totalVotes: 6, gradeCounts: gc(2, 4, 0, 0, 0, 0) },
      { id: 'pandemic', name: 'Pandemic', thumbnail: '', rank: 3, totalVotes: 6, gradeCounts: gc(3, 0, 0, 0, 0, 3) },
    ]),
    dictatorName: 'Alex',
  },
};

// ─── Scenario 9: Veto — Changes Winner ────────────────────────────────────────
const vetoChangesWinner: MockScenario = {
  id: 'mock-veto-changes-winner',
  label: 'Veto — Changes Winner',
  description: 'The top-rated game has one Hard Pass — the veto knocks it out and the runner-up wins.',
  tally: {
    ballotId: 0,
    ballotName: 'One Dissenting Vote',
    officialMethod: 'ivstar',
    voteCount: 5,
    mj: [
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 1, totalVotes: 5, gradeCounts: gc(4, 0, 0, 0, 0, 1) },
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 2, totalVotes: 5, gradeCounts: gc(2, 3, 0, 0, 0, 0) },
      { id: 'azul', name: 'Azul', thumbnail: '', rank: 3, totalVotes: 5, gradeCounts: gc(0, 2, 3, 0, 0, 0) },
    ],
    star: [
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 5,
        starScore: 22,
        inRunoff: true,
        gradeCounts: gc(2, 3, 0, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 5,
        starScore: 20,
        inRunoff: true,
        gradeCounts: gc(4, 0, 0, 0, 0, 1),
      },
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 3,
        totalVotes: 5,
        starScore: 17,
        gradeCounts: gc(0, 2, 3, 0, 0, 0),
      },
    ],
    ivmj: [
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 5, gradeCounts: gc(2, 3, 0, 0, 0, 0) },
      { id: 'azul', name: 'Azul', thumbnail: '', rank: 2, totalVotes: 5, gradeCounts: gc(0, 2, 3, 0, 0, 0) },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 3,
        totalVotes: 5,
        vetoed: true,
        hardPassCount: 1,
        gradeCounts: gc(4, 0, 0, 0, 0, 1),
      },
    ],
    ivstar: [
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 5,
        starScore: 22,
        inRunoff: true,
        gradeCounts: gc(2, 3, 0, 0, 0, 0),
      },
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 2,
        totalVotes: 5,
        starScore: 17,
        inRunoff: true,
        gradeCounts: gc(0, 2, 3, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 3,
        totalVotes: 5,
        starScore: 20,
        vetoed: true,
        hardPassCount: 1,
        gradeCounts: gc(4, 0, 0, 0, 0, 1),
      },
    ],
    borda: [
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 5,
        bordaScore: 8,
        gradeCounts: gc(2, 3, 0, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 5,
        bordaScore: 7,
        gradeCounts: gc(4, 0, 0, 0, 0, 1),
      },
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 3,
        totalVotes: 5,
        bordaScore: 5,
        gradeCounts: gc(0, 2, 3, 0, 0, 0),
      },
    ],
    irv: [
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 5, gradeCounts: gc(2, 3, 0, 0, 0, 0) },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 5,
        irvElimRound: 2,
        gradeCounts: gc(4, 0, 0, 0, 0, 1),
      },
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 3,
        totalVotes: 5,
        irvElimRound: 1,
        gradeCounts: gc(0, 2, 3, 0, 0, 0),
      },
    ],
    condorcet: [
      {
        id: 'wingspan',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 5,
        pairwiseWins: 2,
        gradeCounts: gc(2, 3, 0, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 5,
        pairwiseWins: 1,
        gradeCounts: gc(4, 0, 0, 0, 0, 1),
      },
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 3,
        totalVotes: 5,
        pairwiseWins: 0,
        gradeCounts: gc(0, 2, 3, 0, 0, 0),
      },
    ],
    condorcetParadox: false,
    dictator: d([
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 1, totalVotes: 5, gradeCounts: gc(4, 0, 0, 0, 0, 1) },
      { id: 'wingspan', name: 'Wingspan', thumbnail: '', rank: 2, totalVotes: 5, gradeCounts: gc(2, 3, 0, 0, 0, 0) },
      { id: 'azul', name: 'Azul', thumbnail: '', rank: 3, totalVotes: 5, gradeCounts: gc(0, 2, 3, 0, 0, 0) },
    ]),
    dictatorName: 'Sam',
  },
};

// ─── Scenario: Maximum Disagreement ──────────────────────────────────────────
// 7 voters, 5 games, engineered so that five of the eight methods pick five
// different winners:
//   MJ        → Azul     (polarizer with 4 excellents gives median=excellent)
//   STAR      → Brass    (score leader, wins runoff on broad high ratings)
//   Borda     → Brass    (consistent top-half ranking)
//   IRV       → Brass    (survives eliminations after redistribution)
//   Condorcet → Brass    (beats every other game head-to-head)
//   IV·STAR   → Dominion (Brass & Azul vetoed for hard-passes; Dom beats Catan in runoff)
//   IV·MJ     → Catan    (same veto, but Catan's median verygood > Dom's good)
//   Dictator  → Everdell (Sam, the last voter, rates Everdell excellent)
// Winner distinct count across the 8 methods: 5.
// Ballots verified by running the real voting functions against synthesized
// grades before committing.
const maxDisagree: MockScenario = {
  id: 'mock-max-disagree',
  label: 'Maximum Disagreement',
  description: 'Five different winners across eight methods — polarizer, consensus, vetoes, and a dictator finale.',
  tally: {
    ballotId: 0,
    ballotName: 'Five-Way Split',
    officialMethod: 'ivstar',
    voteCount: 7,
    mj: [
      { id: 'azul', name: 'Azul', thumbnail: '', rank: 1, totalVotes: 7, gradeCounts: gc(4, 0, 0, 0, 0, 3) },
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        gradeCounts: gc(3, 3, 0, 0, 0, 1),
      },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 3, totalVotes: 7, gradeCounts: gc(0, 4, 3, 0, 0, 0) },
      { id: 'dom', name: 'Dominion', thumbnail: '', rank: 4, totalVotes: 7, gradeCounts: gc(2, 1, 4, 0, 0, 0) },
      { id: 'ever', name: 'Everdell', thumbnail: '', rank: 5, totalVotes: 7, gradeCounts: gc(1, 0, 0, 0, 0, 6) },
    ],
    star: [
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        starScore: 27,
        inRunoff: true,
        gradeCounts: gc(3, 3, 0, 0, 0, 1),
      },
      {
        id: 'dom',
        name: 'Dominion',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        starScore: 26,
        inRunoff: true,
        gradeCounts: gc(2, 1, 4, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        starScore: 25,
        gradeCounts: gc(0, 4, 3, 0, 0, 0),
      },
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 4,
        totalVotes: 7,
        starScore: 20,
        gradeCounts: gc(4, 0, 0, 0, 0, 3),
      },
      {
        id: 'ever',
        name: 'Everdell',
        thumbnail: '',
        rank: 5,
        totalVotes: 7,
        starScore: 5,
        gradeCounts: gc(1, 0, 0, 0, 0, 6),
      },
    ],
    ivmj: [
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 1, totalVotes: 7, gradeCounts: gc(0, 4, 3, 0, 0, 0) },
      { id: 'dom', name: 'Dominion', thumbnail: '', rank: 2, totalVotes: 7, gradeCounts: gc(2, 1, 4, 0, 0, 0) },
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        vetoed: true,
        hardPassCount: 3,
        gradeCounts: gc(4, 0, 0, 0, 0, 3),
      },
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 4,
        totalVotes: 7,
        vetoed: true,
        hardPassCount: 1,
        gradeCounts: gc(3, 3, 0, 0, 0, 1),
      },
      {
        id: 'ever',
        name: 'Everdell',
        thumbnail: '',
        rank: 5,
        totalVotes: 7,
        vetoed: true,
        hardPassCount: 6,
        gradeCounts: gc(1, 0, 0, 0, 0, 6),
      },
    ],
    ivstar: [
      {
        id: 'dom',
        name: 'Dominion',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        starScore: 26,
        inRunoff: true,
        gradeCounts: gc(2, 1, 4, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        starScore: 25,
        inRunoff: true,
        gradeCounts: gc(0, 4, 3, 0, 0, 0),
      },
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        starScore: 20,
        vetoed: true,
        hardPassCount: 3,
        gradeCounts: gc(4, 0, 0, 0, 0, 3),
      },
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 4,
        totalVotes: 7,
        starScore: 27,
        vetoed: true,
        hardPassCount: 1,
        gradeCounts: gc(3, 3, 0, 0, 0, 1),
      },
      {
        id: 'ever',
        name: 'Everdell',
        thumbnail: '',
        rank: 5,
        totalVotes: 7,
        starScore: 5,
        vetoed: true,
        hardPassCount: 6,
        gradeCounts: gc(1, 0, 0, 0, 0, 6),
      },
    ],
    borda: [
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        bordaScore: 20,
        gradeCounts: gc(3, 3, 0, 0, 0, 1),
      },
      {
        id: 'dom',
        name: 'Dominion',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        bordaScore: 16.5,
        gradeCounts: gc(2, 1, 4, 0, 0, 0),
      },
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        bordaScore: 15,
        gradeCounts: gc(4, 0, 0, 0, 0, 3),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 4,
        totalVotes: 7,
        bordaScore: 13.5,
        gradeCounts: gc(0, 4, 3, 0, 0, 0),
      },
      {
        id: 'ever',
        name: 'Everdell',
        thumbnail: '',
        rank: 5,
        totalVotes: 7,
        bordaScore: 5,
        gradeCounts: gc(1, 0, 0, 0, 0, 6),
      },
    ],
    irv: [
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        gradeCounts: gc(3, 3, 0, 0, 0, 1),
      },
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        irvElimRound: 4,
        gradeCounts: gc(4, 0, 0, 0, 0, 3),
      },
      {
        id: 'ever',
        name: 'Everdell',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        irvElimRound: 3,
        gradeCounts: gc(1, 0, 0, 0, 0, 6),
      },
      {
        id: 'dom',
        name: 'Dominion',
        thumbnail: '',
        rank: 4,
        totalVotes: 7,
        irvElimRound: 2,
        gradeCounts: gc(2, 1, 4, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 5,
        totalVotes: 7,
        irvElimRound: 1,
        gradeCounts: gc(0, 4, 3, 0, 0, 0),
      },
    ],
    condorcet: [
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        pairwiseWins: 4,
        gradeCounts: gc(3, 3, 0, 0, 0, 1),
      },
      {
        id: 'dom',
        name: 'Dominion',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        pairwiseWins: 3,
        gradeCounts: gc(2, 1, 4, 0, 0, 0),
      },
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        pairwiseWins: 2,
        gradeCounts: gc(4, 0, 0, 0, 0, 3),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 4,
        totalVotes: 7,
        pairwiseWins: 1,
        gradeCounts: gc(0, 4, 3, 0, 0, 0),
      },
      {
        id: 'ever',
        name: 'Everdell',
        thumbnail: '',
        rank: 5,
        totalVotes: 7,
        pairwiseWins: 0,
        gradeCounts: gc(1, 0, 0, 0, 0, 6),
      },
    ],
    condorcetParadox: false,
    dictator: d([
      { id: 'ever', name: 'Everdell', thumbnail: '', rank: 1, totalVotes: 7, gradeCounts: gc(1, 0, 0, 0, 0, 6) },
      { id: 'dom', name: 'Dominion', thumbnail: '', rank: 2, totalVotes: 7, gradeCounts: gc(2, 1, 4, 0, 0, 0) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 3, totalVotes: 7, gradeCounts: gc(0, 4, 3, 0, 0, 0) },
      { id: 'azul', name: 'Azul', thumbnail: '', rank: 4, totalVotes: 7, gradeCounts: gc(4, 0, 0, 0, 0, 3) },
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 5,
        totalVotes: 7,
        gradeCounts: gc(3, 3, 0, 0, 0, 1),
      },
    ]),
    dictatorName: 'Sam',
  },
};

// ─── Scenario 11: Condorcet Paradox (asymmetric) ─────────────────────────────
// 7 voters, 3 candidates — a genuine cycle where grades differ between candidates.
//   Group A (3 voters): Azul=E, Brass=VG, Catan=Avg  →  Azul > Brass > Catan
//   Group B (3 voters): Brass=E, Catan=VG, Azul=Good →  Brass > Catan > Azul
//   Group C (1 voter):  Catan=E, Azul=VG,  Brass=Good → Catan > Azul > Brass
//
// Pairwise head-to-head:
//   Azul  beats Brass  4-3 (groups A+C prefer Azul)
//   Brass beats Catan  6-1 (groups A+B prefer Brass)
//   Catan beats Azul   4-3 (groups B+C prefer Catan)
// → Azul > Brass > Catan > Azul: genuine cycle, no Condorcet winner.
//
// Other methods split: MJ/Borda pick Brass (consistent highs), STAR/IRV pick Azul
// (runoff flip from Brass). Dictator (lone Catan fan, "Morgan") picks Catan.
const condorcetCycle: MockScenario = {
  id: 'mock-condorcet-cycle',
  label: 'Condorcet Cycle',
  description: 'Azul>Brass>Catan>Azul — a real cycle with different grades per candidate, not just a perfect tie.',
  tally: {
    ballotId: 0,
    ballotName: 'Rock Paper Scissors',
    officialMethod: 'condorcet',
    voteCount: 7,
    // Grade distributions:
    //   Azul:  3E (grpA) + 1VG (grpC) + 3Good (grpB) → gc(3,1,3,0,0,0)
    //   Brass: 3VG (grpA) + 3E (grpB) + 1Good (grpC) → gc(3,3,1,0,0,0)
    //   Catan: 3E→Avg (grpA) + 3VG (grpB) + 1E (grpC) → gc(1,3,0,3,0,0)
    // MJ medians: Azul=VG (lean neutral), Brass=VG (lean up) → Brass wins MJ
    mj: [
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        gradeCounts: gc(3, 3, 1, 0, 0, 0),
      },
      { id: 'azul', name: 'Azul', thumbnail: '', rank: 2, totalVotes: 7, gradeCounts: gc(3, 1, 3, 0, 0, 0) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 3, totalVotes: 7, gradeCounts: gc(1, 3, 0, 3, 0, 0) },
    ],
    // STAR scores: Brass=30, Azul=28, Catan=23. Top 2: Brass/Azul.
    // Runoff: grpA(3) prefer Azul(E>VG), grpB(3) prefer Brass(E>Good), grpC(1) prefer Azul(VG>Good)
    // Azul wins runoff 4-3. STAR: Azul wins.
    star: [
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        starScore: 28,
        inRunoff: true,
        gradeCounts: gc(3, 1, 3, 0, 0, 0),
      },
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        starScore: 30,
        inRunoff: true,
        gradeCounts: gc(3, 3, 1, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        starScore: 23,
        gradeCounts: gc(1, 3, 0, 3, 0, 0),
      },
    ],
    // No Hard Passes in any camp → no vetoes. IV = base method.
    ivmj: [
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        gradeCounts: gc(3, 3, 1, 0, 0, 0),
      },
      { id: 'azul', name: 'Azul', thumbnail: '', rank: 2, totalVotes: 7, gradeCounts: gc(3, 1, 3, 0, 0, 0) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 3, totalVotes: 7, gradeCounts: gc(1, 3, 0, 3, 0, 0) },
    ],
    ivstar: [
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        starScore: 28,
        inRunoff: true,
        gradeCounts: gc(3, 1, 3, 0, 0, 0),
      },
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        starScore: 30,
        inRunoff: true,
        gradeCounts: gc(3, 3, 1, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        starScore: 23,
        gradeCounts: gc(1, 3, 0, 3, 0, 0),
      },
    ],
    // Borda: Brass=9, Azul=7, Catan=5
    borda: [
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        bordaScore: 9,
        gradeCounts: gc(3, 3, 1, 0, 0, 0),
      },
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        bordaScore: 7,
        gradeCounts: gc(3, 1, 3, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        bordaScore: 5,
        gradeCounts: gc(1, 3, 0, 3, 0, 0),
      },
    ],
    // IRV: Catan elim round 1 (1 vote → Azul). Round 2: Azul=4, Brass=3. Azul wins.
    irv: [
      { id: 'azul', name: 'Azul', thumbnail: '', rank: 1, totalVotes: 7, gradeCounts: gc(3, 1, 3, 0, 0, 0) },
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 2,
        totalVotes: 7,
        irvElimRound: 2,
        gradeCounts: gc(3, 3, 1, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        irvElimRound: 1,
        gradeCounts: gc(1, 3, 0, 3, 0, 0),
      },
    ],
    // Condorcet: each candidate has 1 pairwise win. Cycle! hasParadox = true.
    condorcet: [
      {
        id: 'azul',
        name: 'Azul',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        pairwiseWins: 1,
        gradeCounts: gc(3, 1, 3, 0, 0, 0),
      },
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        pairwiseWins: 1,
        gradeCounts: gc(3, 3, 1, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 1,
        totalVotes: 7,
        pairwiseWins: 1,
        gradeCounts: gc(1, 3, 0, 3, 0, 0),
      },
    ],
    condorcetParadox: true,
    // Dictator: Morgan (the lone Group C voter, last to vote) picks Catan
    dictator: d([
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 1, totalVotes: 7, gradeCounts: gc(1, 3, 0, 3, 0, 0) },
      { id: 'azul', name: 'Azul', thumbnail: '', rank: 2, totalVotes: 7, gradeCounts: gc(3, 1, 3, 0, 0, 0) },
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 3,
        totalVotes: 7,
        gradeCounts: gc(3, 3, 1, 0, 0, 0),
      },
    ]),
    dictatorName: 'Morgan',
  },
};

// ─── Scenario 12: Tennessee Capital (Condorcet vs IRV) ───────────────────────
// Classic political science example, adapted with board games as city names.
// 20 voters split into 4 regional camps:
//   Memphis   fans (8): Memphis=E, Nashville=VG, Chattanooga=Good, Knoxville=P
//   Nashville fans (5): Nashville=E, Chattanooga=VG, Knoxville=Good, Memphis=P
//   Chattanooga fans (3): Chattanooga=E, Knoxville=VG, Nashville=Good, Memphis=P
//   Knoxville fans (4): Knoxville=E, Chattanooga=VG, Nashville=Good, Memphis=P
//
// Key results:
//   Memphis has the plurality (8/20 = 40%) but loses every head-to-head.
//   Nashville is the Condorcet winner (beats all others pairwise).
//   IRV: Chattanooga eliminated → Knoxville; Nashville eliminated → Knoxville.
//   Knoxville wins IRV despite Nashville being the true consensus pick!
//   Implicit Veto knocks out Memphis AND Knoxville (both have Hard Passes).
const tennessee: MockScenario = {
  id: 'mock-tennessee',
  label: 'Tennessee Capital',
  description: 'Memphis has plurality but Nashville wins everything else — except IRV, which picks Knoxville.',
  tally: {
    ballotId: 0,
    ballotName: 'Tennessee Board Game Championship',
    officialMethod: 'condorcet',
    voteCount: 20,
    // Grade distributions (20 voters):
    //   Memphis:     E=8(Mem), P=12(Nash+Chat+Knox)      → gc(8,0,0,0,0,12)
    //   Nashville:   E=5(Nash), VG=8(Mem), Good=7(C+K)  → gc(5,8,7,0,0,0)
    //   Chattanooga: E=3(Chat), VG=9(Nash+Knox), Good=8(Mem) → gc(3,9,8,0,0,0)
    //   Knoxville:   E=4(Knox), VG=3(Chat), Good=5(Nash), P=8(Mem) → gc(4,3,5,0,0,8)
    // MJ medians: Nashville=VG, Chattanooga=VG, Knoxville=Good, Memphis=P(Hard Pass)
    // Nashville lean: above=5, below=7. Chat lean: above=3, below=8. Nashville wins.
    mj: [
      { id: 'nash', name: 'Nashville', thumbnail: '', rank: 1, totalVotes: 20, gradeCounts: gc(5, 8, 7, 0, 0, 0) },
      { id: 'chat', name: 'Chattanooga', thumbnail: '', rank: 2, totalVotes: 20, gradeCounts: gc(3, 9, 8, 0, 0, 0) },
      { id: 'knox', name: 'Knoxville', thumbnail: '', rank: 3, totalVotes: 20, gradeCounts: gc(4, 3, 5, 0, 0, 8) },
      { id: 'mem', name: 'Memphis', thumbnail: '', rank: 4, totalVotes: 20, gradeCounts: gc(8, 0, 0, 0, 0, 12) },
    ],
    // STAR scores: Nashville=78, Chattanooga=75, Knoxville=47, Memphis=40
    // Runoff Nashville vs Chattanooga: Mem(8)+Nash(5)=13 prefer Nash, Chat(3)+Knox(4)=7 prefer Chat
    star: [
      {
        id: 'nash',
        name: 'Nashville',
        thumbnail: '',
        rank: 1,
        totalVotes: 20,
        starScore: 78,
        inRunoff: true,
        gradeCounts: gc(5, 8, 7, 0, 0, 0),
      },
      {
        id: 'chat',
        name: 'Chattanooga',
        thumbnail: '',
        rank: 2,
        totalVotes: 20,
        starScore: 75,
        inRunoff: true,
        gradeCounts: gc(3, 9, 8, 0, 0, 0),
      },
      {
        id: 'knox',
        name: 'Knoxville',
        thumbnail: '',
        rank: 3,
        totalVotes: 20,
        starScore: 47,
        gradeCounts: gc(4, 3, 5, 0, 0, 8),
      },
      {
        id: 'mem',
        name: 'Memphis',
        thumbnail: '',
        rank: 4,
        totalVotes: 20,
        starScore: 40,
        gradeCounts: gc(8, 0, 0, 0, 0, 12),
      },
    ],
    // IV: Memphis has 12 HP, Knoxville has 8 HP. Min HP = 0 (Nash, Chat). Both vetoed.
    ivmj: [
      { id: 'nash', name: 'Nashville', thumbnail: '', rank: 1, totalVotes: 20, gradeCounts: gc(5, 8, 7, 0, 0, 0) },
      { id: 'chat', name: 'Chattanooga', thumbnail: '', rank: 2, totalVotes: 20, gradeCounts: gc(3, 9, 8, 0, 0, 0) },
      {
        id: 'knox',
        name: 'Knoxville',
        thumbnail: '',
        rank: 3,
        totalVotes: 20,
        vetoed: true,
        hardPassCount: 8,
        gradeCounts: gc(4, 3, 5, 0, 0, 8),
      },
      {
        id: 'mem',
        name: 'Memphis',
        thumbnail: '',
        rank: 4,
        totalVotes: 20,
        vetoed: true,
        hardPassCount: 12,
        gradeCounts: gc(8, 0, 0, 0, 0, 12),
      },
    ],
    ivstar: [
      {
        id: 'nash',
        name: 'Nashville',
        thumbnail: '',
        rank: 1,
        totalVotes: 20,
        starScore: 78,
        inRunoff: true,
        gradeCounts: gc(5, 8, 7, 0, 0, 0),
      },
      {
        id: 'chat',
        name: 'Chattanooga',
        thumbnail: '',
        rank: 2,
        totalVotes: 20,
        starScore: 75,
        inRunoff: true,
        gradeCounts: gc(3, 9, 8, 0, 0, 0),
      },
      {
        id: 'knox',
        name: 'Knoxville',
        thumbnail: '',
        rank: 3,
        totalVotes: 20,
        starScore: 47,
        vetoed: true,
        hardPassCount: 8,
        gradeCounts: gc(4, 3, 5, 0, 0, 8),
      },
      {
        id: 'mem',
        name: 'Memphis',
        thumbnail: '',
        rank: 4,
        totalVotes: 20,
        starScore: 40,
        vetoed: true,
        hardPassCount: 12,
        gradeCounts: gc(8, 0, 0, 0, 0, 12),
      },
    ],
    // Borda: Nash=38, Chat=35, Memphis=24, Knox=23
    borda: [
      {
        id: 'nash',
        name: 'Nashville',
        thumbnail: '',
        rank: 1,
        totalVotes: 20,
        bordaScore: 38,
        gradeCounts: gc(5, 8, 7, 0, 0, 0),
      },
      {
        id: 'chat',
        name: 'Chattanooga',
        thumbnail: '',
        rank: 2,
        totalVotes: 20,
        bordaScore: 35,
        gradeCounts: gc(3, 9, 8, 0, 0, 0),
      },
      {
        id: 'mem',
        name: 'Memphis',
        thumbnail: '',
        rank: 3,
        totalVotes: 20,
        bordaScore: 24,
        gradeCounts: gc(8, 0, 0, 0, 0, 12),
      },
      {
        id: 'knox',
        name: 'Knoxville',
        thumbnail: '',
        rank: 4,
        totalVotes: 20,
        bordaScore: 23,
        gradeCounts: gc(4, 3, 5, 0, 0, 8),
      },
    ],
    // IRV: Chat(3) eliminated → Knox. Nash(5) eliminated → Knox. Memphis vs Knox: Knox wins 12-8!
    irv: [
      { id: 'knox', name: 'Knoxville', thumbnail: '', rank: 1, totalVotes: 20, gradeCounts: gc(4, 3, 5, 0, 0, 8) },
      {
        id: 'mem',
        name: 'Memphis',
        thumbnail: '',
        rank: 2,
        totalVotes: 20,
        irvElimRound: 3,
        gradeCounts: gc(8, 0, 0, 0, 0, 12),
      },
      {
        id: 'nash',
        name: 'Nashville',
        thumbnail: '',
        rank: 3,
        totalVotes: 20,
        irvElimRound: 2,
        gradeCounts: gc(5, 8, 7, 0, 0, 0),
      },
      {
        id: 'chat',
        name: 'Chattanooga',
        thumbnail: '',
        rank: 4,
        totalVotes: 20,
        irvElimRound: 1,
        gradeCounts: gc(3, 9, 8, 0, 0, 0),
      },
    ],
    // Condorcet: Nashville beats all (58% prefer Nash over Memphis, 65% over Chat/Knox)
    //   Nash: 3 wins. Chat: 2 wins. Knox: 1 win. Memphis: 0 wins.
    condorcet: [
      {
        id: 'nash',
        name: 'Nashville',
        thumbnail: '',
        rank: 1,
        totalVotes: 20,
        pairwiseWins: 3,
        gradeCounts: gc(5, 8, 7, 0, 0, 0),
      },
      {
        id: 'chat',
        name: 'Chattanooga',
        thumbnail: '',
        rank: 2,
        totalVotes: 20,
        pairwiseWins: 2,
        gradeCounts: gc(3, 9, 8, 0, 0, 0),
      },
      {
        id: 'knox',
        name: 'Knoxville',
        thumbnail: '',
        rank: 3,
        totalVotes: 20,
        pairwiseWins: 1,
        gradeCounts: gc(4, 3, 5, 0, 0, 8),
      },
      {
        id: 'mem',
        name: 'Memphis',
        thumbnail: '',
        rank: 4,
        totalVotes: 20,
        pairwiseWins: 0,
        gradeCounts: gc(8, 0, 0, 0, 0, 12),
      },
    ],
    condorcetParadox: false,
    // Dictator: Kyle voted last — a Knoxville fan
    dictator: d([
      { id: 'knox', name: 'Knoxville', thumbnail: '', rank: 1, totalVotes: 20, gradeCounts: gc(4, 3, 5, 0, 0, 8) },
      { id: 'chat', name: 'Chattanooga', thumbnail: '', rank: 2, totalVotes: 20, gradeCounts: gc(3, 9, 8, 0, 0, 0) },
      { id: 'nash', name: 'Nashville', thumbnail: '', rank: 3, totalVotes: 20, gradeCounts: gc(5, 8, 7, 0, 0, 0) },
      { id: 'mem', name: 'Memphis', thumbnail: '', rank: 4, totalVotes: 20, gradeCounts: gc(8, 0, 0, 0, 0, 12) },
    ]),
    dictatorName: 'Kyle',
  },
};

// ─── Scenario: IRV Non-Monotonicity — Baseline ───────────────────────────────
// 17 voters split four ways (the canonical Woodall example — smaller variants
// hit ties). Wingspan wins every method, including IRV. Pairwise comparisons
// form a cycle (Wingspan > Brass > Catan > Wingspan), so Condorcet has no
// winner. Morgan is the last voter, in the brass>wing>catan camp — Dictator
// picks Brass.
//
// IRV rounds: R1 wing=6, brass=6, catan=5 → catan eliminated.
//             R2 wing=11, brass=6 → Wingspan wins.
//
// Companion to irvRaised: raising Wingspan in two ballots makes IRV flip.
const irvSincere: MockScenario = {
  id: 'mock-irv-sincere',
  label: 'IRV — Baseline',
  description: 'Wingspan wins every method, including IRV. Its companion scenario raises Wingspan on two ballots — and IRV kicks Wingspan out.',
  related: { id: 'mock-irv-raised', label: 'IRV — Raising Backfires' },
  tally: {
    ballotId: 0,
    ballotName: 'Board Game Showdown — Baseline Ballots',
    officialMethod: 'irv',
    voteCount: 17,
    mj: [
      { id: 'wing', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 17, gradeCounts: gc(6, 7, 0, 0, 0, 4) },
      { id: 'brass', name: 'Brass Birmingham', thumbnail: '', rank: 2, totalVotes: 17, gradeCounts: gc(6, 6, 0, 0, 0, 5) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 3, totalVotes: 17, gradeCounts: gc(5, 0, 4, 0, 0, 8) },
    ],
    star: [
      {
        id: 'wing',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 17,
        starScore: 58,
        inRunoff: true,
        gradeCounts: gc(6, 7, 0, 0, 0, 4),
      },
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 2,
        totalVotes: 17,
        starScore: 54,
        inRunoff: true,
        gradeCounts: gc(6, 6, 0, 0, 0, 5),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 3,
        totalVotes: 17,
        starScore: 37,
        gradeCounts: gc(5, 0, 4, 0, 0, 8),
      },
    ],
    ivmj: [
      { id: 'wing', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 17, gradeCounts: gc(6, 7, 0, 0, 0, 4) },
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 2,
        totalVotes: 17,
        vetoed: true,
        hardPassCount: 5,
        gradeCounts: gc(6, 6, 0, 0, 0, 5),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 3,
        totalVotes: 17,
        vetoed: true,
        hardPassCount: 8,
        gradeCounts: gc(5, 0, 4, 0, 0, 8),
      },
    ],
    ivstar: [
      {
        id: 'wing',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 17,
        starScore: 58,
        inRunoff: true,
        gradeCounts: gc(6, 7, 0, 0, 0, 4),
      },
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 2,
        totalVotes: 17,
        starScore: 54,
        vetoed: true,
        hardPassCount: 5,
        gradeCounts: gc(6, 6, 0, 0, 0, 5),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 3,
        totalVotes: 17,
        starScore: 37,
        vetoed: true,
        hardPassCount: 8,
        gradeCounts: gc(5, 0, 4, 0, 0, 8),
      },
    ],
    borda: [
      { id: 'wing', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 17, bordaScore: 19, gradeCounts: gc(6, 7, 0, 0, 0, 4) },
      { id: 'brass', name: 'Brass Birmingham', thumbnail: '', rank: 2, totalVotes: 17, bordaScore: 18, gradeCounts: gc(6, 6, 0, 0, 0, 5) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 3, totalVotes: 17, bordaScore: 14, gradeCounts: gc(5, 0, 4, 0, 0, 8) },
    ],
    irv: [
      { id: 'wing', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 17, gradeCounts: gc(6, 7, 0, 0, 0, 4) },
      { id: 'brass', name: 'Brass Birmingham', thumbnail: '', rank: 2, totalVotes: 17, irvElimRound: 2, gradeCounts: gc(6, 6, 0, 0, 0, 5) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 3, totalVotes: 17, irvElimRound: 1, gradeCounts: gc(5, 0, 4, 0, 0, 8) },
    ],
    condorcet: [
      { id: 'wing', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 17, pairwiseWins: 1, gradeCounts: gc(6, 7, 0, 0, 0, 4) },
      { id: 'brass', name: 'Brass Birmingham', thumbnail: '', rank: 1, totalVotes: 17, pairwiseWins: 1, gradeCounts: gc(6, 6, 0, 0, 0, 5) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 1, totalVotes: 17, pairwiseWins: 1, gradeCounts: gc(5, 0, 4, 0, 0, 8) },
    ],
    condorcetParadox: true,
    dictator: d([
      { id: 'brass', name: 'Brass Birmingham', thumbnail: '', rank: 1, totalVotes: 17, gradeCounts: gc(6, 6, 0, 0, 0, 5) },
      { id: 'wing', name: 'Wingspan', thumbnail: '', rank: 2, totalVotes: 17, gradeCounts: gc(6, 7, 0, 0, 0, 4) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 3, totalVotes: 17, gradeCounts: gc(5, 0, 4, 0, 0, 8) },
    ]),
    dictatorName: 'Morgan',
  },
};

// ─── Scenario: IRV Non-Monotonicity — Raised ─────────────────────────────────
// Same 17 voters — Morgan and one peer flip brass>wing>catan to wing>brass>catan
// (raising their second-favorite Wingspan to first). Every score-based method
// still picks Wingspan, and A's scores actually rise. But IRV now eliminates
// Brass first, transfers its ballots to Catan, and Catan wins.
//
// IRV rounds: R1 wing=8, brass=4, catan=5 → brass eliminated.
//             R2 wing=8, catan=9 → Catan wins.
//
// Classic non-monotonicity: raising a candidate caused them to lose.
const irvRaised: MockScenario = {
  id: 'mock-irv-raised',
  label: 'IRV — Raising Backfires',
  description: 'Same ballot as the Baseline — but two voters bump Wingspan to first. IRV now eliminates Brass, transfers the votes to Catan, and Catan wins. Raising Wingspan made Wingspan lose.',
  related: { id: 'mock-irv-sincere', label: 'IRV — Baseline' },
  tally: {
    ballotId: 0,
    ballotName: 'Board Game Showdown — Wingspan Raised',
    officialMethod: 'irv',
    voteCount: 17,
    mj: [
      { id: 'wing', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 17, gradeCounts: gc(8, 5, 0, 0, 0, 4) },
      { id: 'brass', name: 'Brass Birmingham', thumbnail: '', rank: 2, totalVotes: 17, gradeCounts: gc(4, 8, 0, 0, 0, 5) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 3, totalVotes: 17, gradeCounts: gc(5, 0, 4, 0, 0, 8) },
    ],
    star: [
      {
        id: 'wing',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 17,
        starScore: 60,
        inRunoff: true,
        gradeCounts: gc(8, 5, 0, 0, 0, 4),
      },
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 2,
        totalVotes: 17,
        starScore: 52,
        inRunoff: true,
        gradeCounts: gc(4, 8, 0, 0, 0, 5),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 3,
        totalVotes: 17,
        starScore: 37,
        gradeCounts: gc(5, 0, 4, 0, 0, 8),
      },
    ],
    ivmj: [
      { id: 'wing', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 17, gradeCounts: gc(8, 5, 0, 0, 0, 4) },
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 2,
        totalVotes: 17,
        vetoed: true,
        hardPassCount: 5,
        gradeCounts: gc(4, 8, 0, 0, 0, 5),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 3,
        totalVotes: 17,
        vetoed: true,
        hardPassCount: 8,
        gradeCounts: gc(5, 0, 4, 0, 0, 8),
      },
    ],
    ivstar: [
      {
        id: 'wing',
        name: 'Wingspan',
        thumbnail: '',
        rank: 1,
        totalVotes: 17,
        starScore: 60,
        inRunoff: true,
        gradeCounts: gc(8, 5, 0, 0, 0, 4),
      },
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 2,
        totalVotes: 17,
        starScore: 52,
        vetoed: true,
        hardPassCount: 5,
        gradeCounts: gc(4, 8, 0, 0, 0, 5),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 3,
        totalVotes: 17,
        starScore: 37,
        vetoed: true,
        hardPassCount: 8,
        gradeCounts: gc(5, 0, 4, 0, 0, 8),
      },
    ],
    borda: [
      { id: 'wing', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 17, bordaScore: 21, gradeCounts: gc(8, 5, 0, 0, 0, 4) },
      { id: 'brass', name: 'Brass Birmingham', thumbnail: '', rank: 2, totalVotes: 17, bordaScore: 16, gradeCounts: gc(4, 8, 0, 0, 0, 5) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 3, totalVotes: 17, bordaScore: 14, gradeCounts: gc(5, 0, 4, 0, 0, 8) },
    ],
    irv: [
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 1, totalVotes: 17, gradeCounts: gc(5, 0, 4, 0, 0, 8) },
      { id: 'wing', name: 'Wingspan', thumbnail: '', rank: 2, totalVotes: 17, irvElimRound: 2, gradeCounts: gc(8, 5, 0, 0, 0, 4) },
      { id: 'brass', name: 'Brass Birmingham', thumbnail: '', rank: 3, totalVotes: 17, irvElimRound: 1, gradeCounts: gc(4, 8, 0, 0, 0, 5) },
    ],
    condorcet: [
      { id: 'wing', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 17, pairwiseWins: 1, gradeCounts: gc(8, 5, 0, 0, 0, 4) },
      { id: 'brass', name: 'Brass Birmingham', thumbnail: '', rank: 1, totalVotes: 17, pairwiseWins: 1, gradeCounts: gc(4, 8, 0, 0, 0, 5) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 1, totalVotes: 17, pairwiseWins: 1, gradeCounts: gc(5, 0, 4, 0, 0, 8) },
    ],
    condorcetParadox: true,
    dictator: d([
      { id: 'wing', name: 'Wingspan', thumbnail: '', rank: 1, totalVotes: 17, gradeCounts: gc(8, 5, 0, 0, 0, 4) },
      { id: 'brass', name: 'Brass Birmingham', thumbnail: '', rank: 2, totalVotes: 17, gradeCounts: gc(4, 8, 0, 0, 0, 5) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 3, totalVotes: 17, gradeCounts: gc(5, 0, 4, 0, 0, 8) },
    ]),
    dictatorName: 'Morgan',
  },
};

// ─── Scenario: Compromise Wins ───────────────────────────────────────────────
// 11 voters, 3 games. Two factions love a polarizing favorite; a third faction
// backs the compromise that everyone else rates "pretty good." STAR, MJ, Borda,
// Condorcet, and both IV methods all pick the compromise. IRV alone throws the
// compromise out in round 1 (fewest first-place votes) and deadlocks A vs B.
//
//   4 Twilight-fans:  TI=E, CN=VG, Catan=P
//   4 Catan-fans:     Catan=E, CN=VG, TI=P
//   3 Codenames-fans: CN=E, TI=G, Catan=G
//
// Last voter (Riley) is a CN-fan, so Dictator also picks Codenames.
const compromiseWins: MockScenario = {
  id: 'mock-compromise-wins',
  label: 'Compromise Wins',
  description: 'Two factions pick polarizing favorites; a third picks the game everyone tolerates. Seven methods lift the compromise. IRV alone eliminates it and then deadlocks on the polarizers.',
  tally: {
    ballotId: 0,
    ballotName: 'Heavy vs Light vs Everyone-Likes-It',
    officialMethod: 'star',
    voteCount: 11,
    mj: [
      { id: 'cn', name: 'Codenames', thumbnail: '', rank: 1, totalVotes: 11, gradeCounts: gc(3, 8, 0, 0, 0, 0) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 2, totalVotes: 11, gradeCounts: gc(4, 0, 3, 0, 0, 4) },
      { id: 'ti', name: 'Twilight Imperium', thumbnail: '', rank: 3, totalVotes: 11, gradeCounts: gc(4, 0, 3, 0, 0, 4) },
    ],
    star: [
      {
        id: 'cn',
        name: 'Codenames',
        thumbnail: '',
        rank: 1,
        totalVotes: 11,
        starScore: 47,
        inRunoff: true,
        gradeCounts: gc(3, 8, 0, 0, 0, 0),
      },
      {
        id: 'ti',
        name: 'Twilight Imperium',
        thumbnail: '',
        rank: 2,
        totalVotes: 11,
        starScore: 29,
        inRunoff: true,
        gradeCounts: gc(4, 0, 3, 0, 0, 4),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 3,
        totalVotes: 11,
        starScore: 29,
        gradeCounts: gc(4, 0, 3, 0, 0, 4),
      },
    ],
    ivmj: [
      { id: 'cn', name: 'Codenames', thumbnail: '', rank: 1, totalVotes: 11, gradeCounts: gc(3, 8, 0, 0, 0, 0) },
      {
        id: 'ti',
        name: 'Twilight Imperium',
        thumbnail: '',
        rank: 2,
        totalVotes: 11,
        vetoed: true,
        hardPassCount: 4,
        gradeCounts: gc(4, 0, 3, 0, 0, 4),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 3,
        totalVotes: 11,
        vetoed: true,
        hardPassCount: 4,
        gradeCounts: gc(4, 0, 3, 0, 0, 4),
      },
    ],
    ivstar: [
      {
        id: 'cn',
        name: 'Codenames',
        thumbnail: '',
        rank: 1,
        totalVotes: 11,
        starScore: 47,
        inRunoff: true,
        gradeCounts: gc(3, 8, 0, 0, 0, 0),
      },
      {
        id: 'ti',
        name: 'Twilight Imperium',
        thumbnail: '',
        rank: 2,
        totalVotes: 11,
        starScore: 29,
        vetoed: true,
        hardPassCount: 4,
        gradeCounts: gc(4, 0, 3, 0, 0, 4),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 3,
        totalVotes: 11,
        starScore: 29,
        vetoed: true,
        hardPassCount: 4,
        gradeCounts: gc(4, 0, 3, 0, 0, 4),
      },
    ],
    borda: [
      { id: 'cn', name: 'Codenames', thumbnail: '', rank: 1, totalVotes: 11, bordaScore: 14, gradeCounts: gc(3, 8, 0, 0, 0, 0) },
      { id: 'ti', name: 'Twilight Imperium', thumbnail: '', rank: 2, totalVotes: 11, bordaScore: 9.5, gradeCounts: gc(4, 0, 3, 0, 0, 4) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 2, totalVotes: 11, bordaScore: 9.5, gradeCounts: gc(4, 0, 3, 0, 0, 4) },
    ],
    irv: [
      { id: 'ti', name: 'Twilight Imperium', thumbnail: '', rank: 1, totalVotes: 11, gradeCounts: gc(4, 0, 3, 0, 0, 4) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 1, totalVotes: 11, gradeCounts: gc(4, 0, 3, 0, 0, 4) },
      { id: 'cn', name: 'Codenames', thumbnail: '', rank: 3, totalVotes: 11, irvElimRound: 1, gradeCounts: gc(3, 8, 0, 0, 0, 0) },
    ],
    condorcet: [
      { id: 'cn', name: 'Codenames', thumbnail: '', rank: 1, totalVotes: 11, pairwiseWins: 2, gradeCounts: gc(3, 8, 0, 0, 0, 0) },
      { id: 'ti', name: 'Twilight Imperium', thumbnail: '', rank: 2, totalVotes: 11, pairwiseWins: 0, gradeCounts: gc(4, 0, 3, 0, 0, 4) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 2, totalVotes: 11, pairwiseWins: 0, gradeCounts: gc(4, 0, 3, 0, 0, 4) },
    ],
    condorcetParadox: false,
    dictator: d([
      { id: 'cn', name: 'Codenames', thumbnail: '', rank: 1, totalVotes: 11, gradeCounts: gc(3, 8, 0, 0, 0, 0) },
      { id: 'ti', name: 'Twilight Imperium', thumbnail: '', rank: 2, totalVotes: 11, gradeCounts: gc(4, 0, 3, 0, 0, 4) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 2, totalVotes: 11, gradeCounts: gc(4, 0, 3, 0, 0, 4) },
    ]),
    dictatorName: 'Riley',
  },
};

// ─── Scenario: Borda Burying — Honest ────────────────────────────────────────
// 11 voters, 3 games. Codenames is the broad-consensus compromise.
//   5 Brass-fans: Brass=E, Codenames=VG, Catan=G
//   4 Catan-fans: Catan=E, Codenames=VG, Brass=G
//   2 Codenames-fans: Codenames=E, Brass=VG, Catan=G
// Codenames wins STAR, Borda, Condorcet, IV·STAR (broad support). MJ and IRV
// still pick Brass (first-place strength). Honest baseline for bordaStrategic.
const bordaHonest: MockScenario = {
  id: 'mock-borda-honest',
  label: 'Borda Burying — Honest',
  description: 'Codenames is everyone\u2019s pretty-good compromise — it wins STAR, Borda, and Condorcet. Its companion scenario shows what happens when Brass-fans try to game Borda by burying Codenames.',
  related: { id: 'mock-borda-strategic', label: 'Borda Burying — Strategic' },
  tally: {
    ballotId: 0,
    ballotName: 'Honest Ballots',
    officialMethod: 'borda',
    voteCount: 11,
    mj: [
      { id: 'brass', name: 'Brass Birmingham', thumbnail: '', rank: 1, totalVotes: 11, gradeCounts: gc(5, 2, 4, 0, 0, 0) },
      { id: 'cn', name: 'Codenames', thumbnail: '', rank: 2, totalVotes: 11, gradeCounts: gc(2, 9, 0, 0, 0, 0) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 3, totalVotes: 11, gradeCounts: gc(4, 0, 7, 0, 0, 0) },
    ],
    star: [
      {
        id: 'cn',
        name: 'Codenames',
        thumbnail: '',
        rank: 1,
        totalVotes: 11,
        starScore: 46,
        inRunoff: true,
        gradeCounts: gc(2, 9, 0, 0, 0, 0),
      },
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 2,
        totalVotes: 11,
        starScore: 45,
        inRunoff: true,
        gradeCounts: gc(5, 2, 4, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 3,
        totalVotes: 11,
        starScore: 41,
        gradeCounts: gc(4, 0, 7, 0, 0, 0),
      },
    ],
    ivmj: [
      { id: 'brass', name: 'Brass Birmingham', thumbnail: '', rank: 1, totalVotes: 11, gradeCounts: gc(5, 2, 4, 0, 0, 0) },
      { id: 'cn', name: 'Codenames', thumbnail: '', rank: 2, totalVotes: 11, gradeCounts: gc(2, 9, 0, 0, 0, 0) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 3, totalVotes: 11, gradeCounts: gc(4, 0, 7, 0, 0, 0) },
    ],
    ivstar: [
      {
        id: 'cn',
        name: 'Codenames',
        thumbnail: '',
        rank: 1,
        totalVotes: 11,
        starScore: 46,
        inRunoff: true,
        gradeCounts: gc(2, 9, 0, 0, 0, 0),
      },
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 2,
        totalVotes: 11,
        starScore: 45,
        inRunoff: true,
        gradeCounts: gc(5, 2, 4, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 3,
        totalVotes: 11,
        starScore: 41,
        gradeCounts: gc(4, 0, 7, 0, 0, 0),
      },
    ],
    borda: [
      { id: 'cn', name: 'Codenames', thumbnail: '', rank: 1, totalVotes: 11, bordaScore: 13, gradeCounts: gc(2, 9, 0, 0, 0, 0) },
      { id: 'brass', name: 'Brass Birmingham', thumbnail: '', rank: 2, totalVotes: 11, bordaScore: 12, gradeCounts: gc(5, 2, 4, 0, 0, 0) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 3, totalVotes: 11, bordaScore: 8, gradeCounts: gc(4, 0, 7, 0, 0, 0) },
    ],
    irv: [
      { id: 'brass', name: 'Brass Birmingham', thumbnail: '', rank: 1, totalVotes: 11, gradeCounts: gc(5, 2, 4, 0, 0, 0) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 2, totalVotes: 11, irvElimRound: 2, gradeCounts: gc(4, 0, 7, 0, 0, 0) },
      { id: 'cn', name: 'Codenames', thumbnail: '', rank: 3, totalVotes: 11, irvElimRound: 1, gradeCounts: gc(2, 9, 0, 0, 0, 0) },
    ],
    condorcet: [
      { id: 'cn', name: 'Codenames', thumbnail: '', rank: 1, totalVotes: 11, pairwiseWins: 2, gradeCounts: gc(2, 9, 0, 0, 0, 0) },
      { id: 'brass', name: 'Brass Birmingham', thumbnail: '', rank: 2, totalVotes: 11, pairwiseWins: 1, gradeCounts: gc(5, 2, 4, 0, 0, 0) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 3, totalVotes: 11, pairwiseWins: 0, gradeCounts: gc(4, 0, 7, 0, 0, 0) },
    ],
    condorcetParadox: false,
    dictator: d([
      { id: 'cn', name: 'Codenames', thumbnail: '', rank: 1, totalVotes: 11, gradeCounts: gc(2, 9, 0, 0, 0, 0) },
      { id: 'brass', name: 'Brass Birmingham', thumbnail: '', rank: 2, totalVotes: 11, gradeCounts: gc(5, 2, 4, 0, 0, 0) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 3, totalVotes: 11, gradeCounts: gc(4, 0, 7, 0, 0, 0) },
    ]),
    dictatorName: 'Avery',
  },
};

// ─── Scenario: Borda Burying — Strategic ─────────────────────────────────────
// Same 11 voters, except the 5 Brass-fans strategically bury Codenames —
// rating it Poor instead of VeryGood to knock out the consensus threat.
// STAR: strategy succeeds (Brass flips to #1). Borda: backfires! The burial
// also demoted Codenames below Catan on the Brass-fan ballots, handing Borda
// to Catan. Condorcet becomes a cycle. IV·MJ now vetoes Codenames.
//
// The takeaway: naïve strategic voting is a gamble — it can tip the method you
// care about, and simultaneously break others you don't.
const bordaStrategic: MockScenario = {
  id: 'mock-borda-strategic',
  label: 'Borda Burying — Strategic',
  description: 'Same voters as the Honest ballot, but Brass-fans downgrade Codenames to Poor to kill the compromise. STAR flips to Brass (strategy works). Borda flips to Catan — burying Codenames accidentally elevated Catan on their ballots.',
  related: { id: 'mock-borda-honest', label: 'Borda Burying — Honest' },
  tally: {
    ballotId: 0,
    ballotName: 'Brass-Fans Bury the Compromise',
    officialMethod: 'borda',
    voteCount: 11,
    mj: [
      { id: 'brass', name: 'Brass Birmingham', thumbnail: '', rank: 1, totalVotes: 11, gradeCounts: gc(5, 2, 4, 0, 0, 0) },
      { id: 'cn', name: 'Codenames', thumbnail: '', rank: 2, totalVotes: 11, gradeCounts: gc(2, 4, 0, 0, 0, 5) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 3, totalVotes: 11, gradeCounts: gc(4, 0, 7, 0, 0, 0) },
    ],
    star: [
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 1,
        totalVotes: 11,
        starScore: 45,
        inRunoff: true,
        gradeCounts: gc(5, 2, 4, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 11,
        starScore: 41,
        inRunoff: true,
        gradeCounts: gc(4, 0, 7, 0, 0, 0),
      },
      {
        id: 'cn',
        name: 'Codenames',
        thumbnail: '',
        rank: 3,
        totalVotes: 11,
        starScore: 26,
        gradeCounts: gc(2, 4, 0, 0, 0, 5),
      },
    ],
    ivmj: [
      { id: 'brass', name: 'Brass Birmingham', thumbnail: '', rank: 1, totalVotes: 11, gradeCounts: gc(5, 2, 4, 0, 0, 0) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 2, totalVotes: 11, gradeCounts: gc(4, 0, 7, 0, 0, 0) },
      {
        id: 'cn',
        name: 'Codenames',
        thumbnail: '',
        rank: 3,
        totalVotes: 11,
        vetoed: true,
        hardPassCount: 5,
        gradeCounts: gc(2, 4, 0, 0, 0, 5),
      },
    ],
    ivstar: [
      {
        id: 'brass',
        name: 'Brass Birmingham',
        thumbnail: '',
        rank: 1,
        totalVotes: 11,
        starScore: 45,
        inRunoff: true,
        gradeCounts: gc(5, 2, 4, 0, 0, 0),
      },
      {
        id: 'catan',
        name: 'Catan',
        thumbnail: '',
        rank: 2,
        totalVotes: 11,
        starScore: 41,
        inRunoff: true,
        gradeCounts: gc(4, 0, 7, 0, 0, 0),
      },
      {
        id: 'cn',
        name: 'Codenames',
        thumbnail: '',
        rank: 3,
        totalVotes: 11,
        starScore: 26,
        vetoed: true,
        hardPassCount: 5,
        gradeCounts: gc(2, 4, 0, 0, 0, 5),
      },
    ],
    borda: [
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 1, totalVotes: 11, bordaScore: 13, gradeCounts: gc(4, 0, 7, 0, 0, 0) },
      { id: 'brass', name: 'Brass Birmingham', thumbnail: '', rank: 2, totalVotes: 11, bordaScore: 12, gradeCounts: gc(5, 2, 4, 0, 0, 0) },
      { id: 'cn', name: 'Codenames', thumbnail: '', rank: 3, totalVotes: 11, bordaScore: 8, gradeCounts: gc(2, 4, 0, 0, 0, 5) },
    ],
    irv: [
      { id: 'brass', name: 'Brass Birmingham', thumbnail: '', rank: 1, totalVotes: 11, gradeCounts: gc(5, 2, 4, 0, 0, 0) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 2, totalVotes: 11, irvElimRound: 2, gradeCounts: gc(4, 0, 7, 0, 0, 0) },
      { id: 'cn', name: 'Codenames', thumbnail: '', rank: 3, totalVotes: 11, irvElimRound: 1, gradeCounts: gc(2, 4, 0, 0, 0, 5) },
    ],
    condorcet: [
      { id: 'brass', name: 'Brass Birmingham', thumbnail: '', rank: 1, totalVotes: 11, pairwiseWins: 1, gradeCounts: gc(5, 2, 4, 0, 0, 0) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 1, totalVotes: 11, pairwiseWins: 1, gradeCounts: gc(4, 0, 7, 0, 0, 0) },
      { id: 'cn', name: 'Codenames', thumbnail: '', rank: 1, totalVotes: 11, pairwiseWins: 1, gradeCounts: gc(2, 4, 0, 0, 0, 5) },
    ],
    condorcetParadox: true,
    dictator: d([
      { id: 'cn', name: 'Codenames', thumbnail: '', rank: 1, totalVotes: 11, gradeCounts: gc(2, 4, 0, 0, 0, 5) },
      { id: 'brass', name: 'Brass Birmingham', thumbnail: '', rank: 2, totalVotes: 11, gradeCounts: gc(5, 2, 4, 0, 0, 0) },
      { id: 'catan', name: 'Catan', thumbnail: '', rank: 3, totalVotes: 11, gradeCounts: gc(4, 0, 7, 0, 0, 0) },
    ]),
    dictatorName: 'Avery',
  },
};

// Public scenarios surfaced on the home page, ordered by "wow factor."
// Each is a voting-theory demo, not an empty-state fixture.
export const MOCK_SCENARIOS: MockScenario[] = [
  diverge,
  tennessee,
  condorcetCycle,
  runoffFlip,
  bordaConsensus,
  maxDisagree,
  vetoChangesWinner,
  vetoNodiff,
  irvSincere,
  irvRaised,
  compromiseWins,
  bordaHonest,
  bordaStrategic,
  tie,
  agree,
];

// Admin-only scenarios. Empty/degenerate-state fixtures plus scenarios whose
// voting-theory payoff is too thin for the public showcase.
export const ADMIN_MOCK_SCENARIOS: MockScenario[] = [oneVote, noVotes, vetoOneSurvivor];

// Full set for id lookups (tally page still needs to resolve admin IDs).
export const ALL_MOCK_SCENARIOS: MockScenario[] = [...MOCK_SCENARIOS, ...ADMIN_MOCK_SCENARIOS];

export function getMockScenario(id: string): MockScenario | undefined {
  return ALL_MOCK_SCENARIOS.find((s) => s.id === id);
}
